title: "Pagina de prueba en local"
description: "Esta es la presentación de mi pagina"
baseurl: ""
url: "https://S3iiz4.github.io"
theme: "cvless"

exclude:
  - cvless.gemspec
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
